---
- name: Create Digital Ocean droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: "{{ server.server_name }}"
    size: "{{ profile.provider_config.size }}"
    image: "{{ profile.provider_config.image }}"
    region: "{{ profile.provider_config.region }}"
    ssh_keys: "{{ sudo_user_ssh_keys }}"
    unique_name: yes
    oauth_token: "{{ provider_config.do_api_token | default(lookup('env', 'DO_API_TOKEN')) }}"
    wait_timeout: 500
  register: do_droplet

- name: Set server address
  set_fact:
    server: "{{ server | combine({'address': do_droplet.data.ip_address}) }}"
