---
- name: Create Hetzner server
  hetzner.hcloud.server:
    name: "{{ server.server_name }}"
    hcloud_token: "{{ hcloud_token | default(lookup('env', 'HCLOUD_TOKEN')) }}"
    server_type: "{{ profile.provider_config.server_type }}"
    image: "{{ profile.provider_config.image }}"
    location: "{{ profile.provider_config.location }}"
    backups: "{{ server.backups | default(true) }}"
    ssh_keys: "{{ sudo_user_ssh_keys }}"
  register: hetzner_server

- name: Set server address
  set_fact:
    server: "{{ server | combine({'address': hetzner_server.hcloud_server.ipv4_address}) }}"