---
- name: Create Vultr instance
  vultr.cloud.instance:
    name: "{{ server.server_name }}"
    region: "{{ profile.provider_config.region }}"
    plan: "{{ profile.provider_config.server_plan }}"
    os: "{{ profile.provider_config.image }}"
    ssh_keys: "{{ sudo_user_ssh_keys }}"
    api_key: "{{ provider_config.vultr_api_key | default(lookup('env', 'VULTR_API_KEY')) }}"
    state: present
  register: vultr_instance

- name: Set server address
  set_fact:
    server: "{{ server | combine({'address': vultr_instance.instance.main_ip}) }}"
