---
- name: Validate inputs.
  ansible.builtin.import_tasks: validate-inputs.yml

- name: Set up Debian (when OS is Debian based)
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure email alerts.
  ansible.builtin.include_tasks: email-alerts.yml

- name: Setup MOTD.
  ansible.builtin.include_tasks: motd.yml

- name: Apply security policies to the server.
  ansible.builtin.include_tasks: security.yml

- name: Configure server users.
  ansible.builtin.include_tasks: users.yml