---
namespace: serversideup
name: spin
version: 1.3.1
readme: README.md
authors:
  - Jay Rogers (https://x.com/jaydrogers)
description: The Spin Collection is a collection of Ansible roles that can be used to spin up a Linux server with Docker Swarm.
license_file: LICENSE
tags:
  - serversideup
  - spin
  - linux
  - docker
  - swarm
dependencies:
  ansible.posix: '*'
  community.general: '*'
  community.docker: '*'
  hetzner.hcloud: '*'
  vultr.cloud: '*'
  digitalocean.cloud: '*'
repository: https://github.com/serversideup/ansible-collection-spin
documentation: https://serversideup.net/open-source/spin/docs/
homepage: https://serversideup.net/open-source/spin/
issues: https://github.com/serversideup/ansible-collection-spin/issues
build_ignore:
  - 'new-version.sh'
