server_timezone: "America/Chicago"
server_contact: "otheremail@example.com"
use_passwordless_sudo: false

users:
  - username: alice
    name: Alice Smith
    state: present
    groups: ['sudo']
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1lmyfakeublickeyMVIzwQXBzxxD9b8Erd1FKVvu alice"

  - username: bob
    name: Bob Smith
    state: present
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    groups: ['sudo']
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu bob"

additional_users:
  - username: charlie
    groups: ['sudo']
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1lmyfakeublickeyMVIzwQXBzxxD9b8Erd1FKVvu charlie"

  - username: dana
    name: Dana Smith
    state: present
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    groups: ['sudo']
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu dana"

  - username: nopassword
    name: No Password Test
    state: present
    groups: ['users']
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu nopassword"

docker_user:
  username: dockeruser
  authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu dockeruser"

common_additional_packages:
  - python3-jsondiff
  - python3-yaml
