server_timezone: "America/Chicago"

use_passwordless_sudo: true

users:
  - username: alice
    name: Alice Smith
    state: present
    groups: ['adm', 'sudo']
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1lmyfakeublickeyMVIzwQXBzxxD9b8Erd1FKVvu alice"

  - username: bob
    name: Bob Smith
    state: present
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    groups: ['adm', 'sudo']
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu bob"

additional_users:
  - username: charlie
    groups: ['adm', 'sudo']
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1lmyfakeublickeyMVIzwQXBzxxD9b8Erd1FKVvu charlie"

  - username: dana
    name: Dana Smith
    state: present
    password: "$6$IXlCqhTY2T$nDnDJRcvk59V2yb3O4Z9n0zO70z/xVCllphjrJ.L618OvHfSs1hciwtxUS/UxR7tF5xWcwzRr3eHboiSHFG7I1"
    groups: ['adm', 'sudo']
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu dana"

  - username: nopassword
    name: No Password Test
    state: present
    groups: ['adm', 'sudo']
    shell: "/bin/bash"
    authorized_keys:
      - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu nopassword"

docker_user:
  username: dockeruser
  uid: 8888
  group: dockergroup
  secondary_groups: "docker"
  gid: 8888
  home: "/opt/docker"