---

- name: Validate servers configuration
  ansible.builtin.assert:
    that:
      - item.hardware_profile is defined
      - item.hardware_profile | string | length > 0
      - item.hardware_profile in (hardware_profiles | map(attribute='name') | list)
      - item.environment is defined
      - item.environment | string | length > 0
      - item.environment in (environments | map(attribute='name') | list)
    fail_msg: >-
      Server '{{ item.server_name }}' validation failed:
      {% if item.hardware_profile is not defined or not item.hardware_profile %}
      - Missing required 'hardware_profile'
      {% endif %}
      {% if item.hardware_profile is defined and item.hardware_profile not in (hardware_profiles | map(attribute='name') | list) %}
      - Invalid hardware_profile '{{ item.hardware_profile }}'. Available profiles are: {{ hardware_profiles | map(attribute='name') | list }}
      {% endif %}
      {% if item.environment is not defined or not item.environment %}
      - Missing required 'environment'
      {% endif %}
      {% if item.environment is defined and item.environment not in (environments | map(attribute='name') | list) %}
      - Invalid environment '{{ item.environment }}'. Available environments are: {{ environments | map(attribute='name') | list }}
      {% endif %}
  loop: "{{ servers }}"
  run_once: true
  delegate_to: localhost

- name: Check if any servers are missing an address
  ansible.builtin.set_fact:
    servers_missing_addresses: >-
      {{
        servers | selectattr('address', 'undefined') | map('combine', {
          'provider': hardware_profiles | 
          selectattr('name', 'equalto', item.hardware_profile) | 
          map(attribute='provider') | first
        }) | list
      }}
  loop: "{{ servers }}"

- name: Create servers if any addresses are missing
  ansible.builtin.include_tasks: "create-servers.yml"
  when: servers_missing_addresses | length > 0
