---
- name: Gather SSH keys for sudo users
  set_fact:
    sudo_user_ssh_keys: "{{ users | selectattr('groups', 'contains', 'sudo') | map(attribute='authorized_keys') | flatten | map(attribute='public_key') | list }}"

- name: Create servers that are missing an address
  include_tasks: "providers/{{ hardware_profiles | selectattr('name', 'equalto', item.hardware_profile) | map(attribute='provider') | first }}.yml"
  loop: "{{ servers }}"
  when: item.address is not defined
  vars:
    server: "{{ item }}"
    profile: "{{ hardware_profiles | selectattr('name', 'equalto', item.hardware_profile) | first }}"
    provider_config: "{{ providers | selectattr('name', 'equalto', profile.provider) | first }}"
  register: created_servers

- name: Update .spin.example.yml with new server address
  ansible.builtin.lineinfile:
    path: "@.spin.example.yml"
    insertafter: "^  - server_name: {{ item.server_name }}"
    line: "    address: {{ item.address }}"
    state: present
  loop: "{{ servers }}"
  when: item.address is defined and created_servers.changed

- name: Reload inventory
  meta: refresh_inventory
