---
- name: Get SSH keys for sudo users
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Extract sudo users' SSH keys
      ansible.builtin.set_fact:
        sudo_keys: >-
          {{
            users | selectattr('groups', 'contains', 'sudo') |
            map(attribute='authorized_keys') | flatten |
            map(attribute='public_key') | join('\n')
          }}

    - name: Output keys
      ansible.builtin.debug:
        msg: "{{ sudo_keys }}"