---
- name: Get SSH keys for sudo users
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Extract and output sudo users' SSH keys
      ansible.builtin.debug:
        msg: >-
          {{
            users | selectattr('groups', 'contains', 'sudo') |
            map(attribute='authorized_keys') | flatten |
            map(attribute='public_key') | join('\n')
          }}