---
- name: Get variable value
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display failure if variable_name is not set
      ansible.builtin.fail:
        msg: "variable_name is not set. Use -e variable_name=<name_of_variable>"
      when: variable_name is not defined
      run_once: true

    - name: Create output directory if it doesn't exist
      ansible.builtin.file:
        path: /output
        state: directory
        mode: '0700'
      run_once: true

    - name: Write variable value to file
      ansible.builtin.copy:
        content: "{{ lookup('vars', variable_name) }}"
        dest: "/output/{{ variable_name }}"
        mode: '0600'
      when: variable_name in vars
      run_once: true