---
- name: Get First Manager Host for Environment
  hosts: localhost
  gather_facts: false
  vars:
    ansible_verbosity: 0

  tasks:
    - name: Fail if environment is not set
      ansible.builtin.fail:
        msg: "spin_environment variable is not set. Use -e spin_environment=<env_name>"
      when: spin_environment is not defined

    - name: Get first manager host for environment
      ansible.builtin.set_fact:
        first_manager: "{{ groups['servers_' + spin_environment + '_managers'][0] }}"
      when: groups['servers_' + spin_environment + '_managers'] is defined and groups['servers_' + spin_environment + '_managers'] | length > 0

    - name: Output first manager host
      ansible.builtin.shell: "echo '{{ first_manager }}'"
      register: raw_output
      changed_when: false
      when: first_manager is defined
      
    - name: Print only host
      ansible.builtin.debug:
        msg: "{{ raw_output.stdout }}"
      when: first_manager is defined
      vars:
        ansible_verbosity: 0
      
    - name: Fail if no manager found
      ansible.builtin.fail:
        msg: "No hosts found in servers_{{ spin_environment }}_managers group"
      when: first_manager is not defined
