---
- name: Perform server maintenance tasks.
  hosts: "{{ target | default('all') }}"
  remote_user: "{{ spin_remote_user | default('root') }}"
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o StrictHostKeyChecking=accept-new"
    ansible_python_interpreter: auto_silent
  roles:
    - serversideup.spin.update_server 