---
- name: Setup and provision Docker Swarm servers with Spin.
  hosts: "{{ target | default('all') }}"
  remote_user: "{{ ansible_user | default('root') }}"
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain"
    ansible_python_interpreter: auto_silent
  roles:
    - serversideup.spin.linux_common
    - serversideup.spin.swarm