---
- name: Create servers with the VPS provider of your choice.
  hosts: localhost
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o StrictHostKeyChecking=accept-new"
    ansible_inventory_sources: 
      - "{{ playbook_dir }}/../plugins/inventory/spin-dynamic-inventory.sh"
  tasks:
    - name: Ensure providers, servers, and hardware profiles are defined
      ansible.builtin.fail:
        msg: "You have an invalid configuration in your variables file (usually '.spin.yml'). Be sure providers, servers, and hardware_profiles are defined."
      when: >
        providers is not defined or
        providers is none or
        (providers | default([]) | length == 0) or
        hardware_profiles is not defined or
        hardware_profiles is none or
        (hardware_profiles | default([]) | length == 0)

    - name: Create servers
      include_role:
        name: serversideup.spin.create_server
      when: servers | selectattr('address', 'undefined') | list | length > 0

    - name: Set fact for new servers
      set_fact:
        newly_created_server_ips: "{{ newly_created_server_ips | default({}) }}"
      delegate_facts: true

- name: Configure Docker Swarm servers.
  hosts: "{{ target | default('all') }}"
  remote_user: "{{ (inventory_hostname in (hostvars['localhost']['newly_created_server_ips'] | default({})).values()) | ternary(initial_ssh_user | default('root'), spin_remote_user) }}"
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o StrictHostKeyChecking=accept-new"
    ansible_python_interpreter: auto_silent
    ansible_inventory_sources: 
      - "{{ playbook_dir }}/../plugins/inventory/spin-dynamic-inventory.sh"
  pre_tasks:
    - name: Show error if no hosts found in the target group.
      ansible.builtin.fail:
        msg: "No hosts found in the target group '{{ target | default('all') }}'. Check your inventory configuration."
      when: groups[target | default('all')] | length == 0
      run_once: true
      delegate_to: localhost

  roles:
    - serversideup.spin.linux_common
    - serversideup.spin.swarm
