---
- name: Create servers with the VPS provider of your choice.
  hosts: localhost
  gather_facts: false
  vars:
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o StrictHostKeyChecking=accept-new"
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Check if providers and servers are defined
      ansible.builtin.fail:
        msg: "Providers and servers must be defined in the variables file (usually '.spin.yml')."
      when: >
        providers is not defined or
        providers is none or
        (providers | default([]) | length == 0) or
        servers is not defined or
        servers is none or
        (servers | default([]) | length == 0)

    - name: Create servers
      include_role:
        name: serversideup.spin.create_server
      when: providers is defined and providers|length > 0 and servers is defined and servers|length > 0

    - name: Update inventory with new server IPs
      lineinfile:
        path: "{{ inventory_file_path }}"
        line: "{{ item }}"
      loop: "{{ new_server_ips }}"
      when: new_server_ips is defined

    - name: Reload inventory
      meta: refresh_inventory

- name: Configure Docker Swarm servers.
  hosts: "{{ target | default('all') }}"
  remote_user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Ensure there are hosts in the target group
      fail:
        msg: "No hosts found in the target group."
      when: groups[target | default('all')] | length == 0

  roles:
    - serversideup.spin.linux_common
    - serversideup.spin.swarm
