---
- name: Create servers with the VPS provider of your choice.
  hosts: localhost
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o StrictHostKeyChecking=accept-new"
    ansible_inventory_sources: 
      - "{{ playbook_dir }}/../plugins/inventory/spin-dynamic-inventory.sh"
  tasks:
    - name: Ensure providers, servers, and hardware profiles are defined
      ansible.builtin.fail:
        msg: "You have an invalid configuration in your variables file (usually '.spin.yml'). Be sure providers, servers, and hardware_profiles are defined."
      when: >
        providers is not defined or
        providers is none or
        (providers | default([]) | length == 0) or
        hardware_profiles is not defined or
        hardware_profiles is none or
        (hardware_profiles | default([]) | length == 0)

    - name: Create servers
      include_role:
        name: serversideup.spin.create_server
      when: servers | selectattr('address', 'undefined') | list | length > 0

    - name: Update created servers
      include_role:
        name: serversideup.spin.update_server
      delegate_to: "{{ item.value }}"
      loop: "{{ server_ips | dict2items }}"
      when: server_ips is defined and server_ips | length > 0

- name: Configure Docker Swarm servers.
  hosts: "{{ target | default('all') }}"
  remote_user: "{{ ansible_user | default('root') }}"
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o StrictHostKeyChecking=accept-new"
    ansible_python_interpreter: auto_silent
    ansible_inventory_sources: 
      - "{{ playbook_dir }}/../plugins/inventory/spin-dynamic-inventory.sh"
  pre_tasks:
    - name: Ensure there are hosts in the target group
      ansible.builtin.fail:
        msg: "No hosts found in the target group '{{ target | default('all') }}'. Check your inventory configuration."
      when: groups[target | default('all')] | length == 0
      run_once: true
      delegate_to: localhost

  roles:
    - serversideup.spin.linux_common
    - serversideup.spin.swarm
